FROM caddy
COPY . /usr/share/caddy
COPY Caddyfile /etc/caddy/Caddyfile
ENV BITCOIN_SERVICCE=bitcoin-service
ENV SOLANA_SERVICE=solana-service
ENV ETHEREUM_SERVICE=ethereum-service
ENV MONERO_SERVICE=monero-service